Create project structure
nikola-lisac/priority-tasks-backend pull request #9
Opened 2017-08-14 09:39 UTC by nikola-lisac

2017-08-14 11:43 UTC, cctraining requested changes
I know that we have a task for adding .gitignore file but that task should just update it. I would like to have .gitignore file for this PR. It doesn't make sense to have .gradle and Intellij directories committed.

2017-08-14 15:56 UTC, BojanJakic approved these changes

2017-08-14 16:07 UTC, cctraining requested changes
From my point of view we should stick to https://chris.beams.io/posts/git-commit/

Amend your commit and force push.
Question: Why do we need out directory? We should put it to .gitignore or?

2017-08-15 16:37 UTC, DraganKec approved these changes
Will we have integration branch or we marge directli on master branch?

2017-08-16 08:21 UTC, GojkovicGoran approved these changes

2017-08-16 08:39 UTC, cctraining approved these changes

2017-08-16 08:42 UTC, merged